devops-ia/helm-opencti

README.md, README.md.gotmpl, opencti/Chart.yaml, opencti/ci/ci-values.yaml
* Increase deps version
* Upgrade to 6.2.3 OpenCTI
=> feat: upgrade deps and increase OpenCTI version

opencti/Chart.yaml, opencti/templates/connector/deployment.yaml
Fixed `OPENCTI_TOKEN` reference on `connector` deployment.
close #3
=> Fix environment reference OPENCTI_TOKEN #3

opencti/Chart.yaml
Bump OpenCTI version:
- :information_source: Current: `6.2.11`
- :up: Upgrade: `6.2.12`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.2.12
=> [opencti] Bump version to 6.2.12

charts/opencti/templates/server/deployment.yaml, charts/opencti/templates/tests/test-connection.yaml, charts/opencti/templates/worker/deployment.yaml
Currently, initContainer image busybox:latest can only be pulled from docker hub. And it can't be pulled from a private image registry. This PR intends to resolve this issue.
@ialejandro , let me know your comments/feedback.
=> Allow initContainer images to be pulled from private registry

charts/opencti/Chart.yaml, charts/opencti/README.md
opensearch
----------
* **Current**: `2.22.0`
* **Upgrade**: `2.22.1`
* **Changelog**: https://github.com/opensearch-project/helm-charts/releases/tag/opensearch/opensearch/2.22.1
minio
-----
* **Current**: `14.6.32`
* **Upgrade**: `14.7.1`
* **Changelog**: https://github.com/bitnami/charts/releases/tag/minio/14.7.1
elasticsearch
-------------
* **Current**: `21.3.6`
* **Upgrade**: `21.3.8`
* Changelog: https://github.com/bitnami/charts/releases/tag/elasticsearch/21.3.8
=> [opencti] upgrade minor dependencies (2024-08-19)

charts/opencti/Chart.yaml, charts/opencti/README.md
opensearch
----------
* **Current**: `2.22.1`
* **Upgrade**: `2.23.0`
* **Changelog**: https://github.com/opensearch-project/helm-charts/releases/tag/opensearch/opensearch/2.23.0
=> [opencti] upgrade minor dependencies (2024-08-26)

charts/opencti/ci/ci-values.yaml, charts/opencti/templates/connector/deployment.yaml, charts/opencti/values.yaml
* Fix annotations for pod and deployment
- fixes #32
N/A
=> fix: pod and deployment annotations

.github/workflows/release.yaml, charts/opencti/artifacthub-repo.yml
* Set artifacthub file to push on Github Package
- closes #38
N/A
=> fix: oras push helm sign for artifacthub

charts/opencti/templates/server/deployment.yaml, charts/opencti/templates/worker/deployment.yaml
- Use `default (include "opencti.fullname" .)` instead `$.Release.Name` on `worker` deployment.
- closes #41 
N/A
=> fix: release name on ready-checker

charts/opencti/README.md, charts/opencti/ci/ci-common-values.yaml, charts/opencti/docs/examples.md, charts/opencti/templates/connector/deployment.yaml, charts/opencti/values.yaml
* Update docs
* Add initContainer (readyChecker) on connector
- closes #43 
N/A
=> fix: add enable ready-checker connector

charts/opencti/README.md, charts/opencti/templates/connector/deployment.yaml, charts/opencti/templates/server/deployment.yaml, charts/opencti/templates/worker/deployment.yaml, charts/opencti/values.yaml
* Improve imagePullSecrets conditional
* Clean code
* Add podAnnotations and podLabels
* Add volumes
* Improve docs
* fixes #46 
N/A
=> feat: allow volumes on server and worker

charts/opencti/Chart.yaml
- :information_source: Current: `6.2.16`
- :up: Upgrade: `6.2.18`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.2.18
=> [opencti] new release: 6.2.18

charts/opencti/Chart.yaml, charts/opencti/README.md
redis
-----
* **Current**: `19.6.4`
* **Upgrade**: `20.0.3`
* **Changelog**: https://github.com/bitnami/charts/releases/tag/redis/20.0.3
rabbitmq
--------
* **Current**: `14.6.6`
* **Upgrade**: `14.6.9`
* **Changelog**: https://github.com/bitnami/charts/releases/tag/rabbitmq/14.6.9
opensearch
----------
* **Current**: `2.23.0`
* **Upgrade**: `2.23.1`
* **Changelog**: https://github.com/opensearch-project/helm-charts/releases/tag/opensearch/opensearch/2.23.1
minio
-----
* **Current**: `14.7.1`
* **Upgrade**: `14.7.4`
* **Changelog**: https://github.com/bitnami/charts/releases/tag/minio/14.7.4
elasticsearch
-------------
* **Current**: `21.3.8`
* **Upgrade**: `21.3.10`
* Changelog: https://github.com/bitnami/charts/releases/tag/elasticsearch/21.3.10
=> [opencti] upgrade major dependencies (2024-09-01)

charts/opencti/Chart.yaml, charts/opencti/README.md
opensearch
----------
* **Current**: `2.23.1`
* **Upgrade**: `2.23.2`
* **Changelog**: https://github.com/opensearch-project/helm-charts/releases/tag/opensearch/opensearch/2.23.2
minio
-----
* **Current**: `14.7.4`
* **Upgrade**: `14.7.5`
* **Changelog**: https://github.com/bitnami/charts/releases/tag/minio/14.7.5
elasticsearch
-------------
* **Current**: `21.3.10`
* **Upgrade**: `21.3.13`
* **Changelog**: https://github.com/bitnami/charts/releases/tag/elasticsearch/21.3.13
redis
-----
* **Current**: `20.0.3`
* **Upgrade**: `20.0.5`
* Changelog: https://github.com/bitnami/charts/releases/tag/redis/20.0.5
=> [opencti] upgrade minor dependencies (2024-09-09)

charts/opencti/Chart.yaml, charts/opencti/README.md
elasticsearch
-------------
* **Current**: `21.3.13`
* **Upgrade**: `21.3.16`
* **Changelog**: https://github.com/bitnami/charts/releases/tag/elasticsearch/21.3.16
redis
-----
* **Current**: `20.0.5`
* **Upgrade**: `20.1.3`
* **Changelog**: https://github.com/bitnami/charts/releases/tag/redis/20.1.3
rabbitmq
--------
* **Current**: `14.6.9`
* **Upgrade**: `14.7.0`
* **Changelog**: https://github.com/bitnami/charts/releases/tag/rabbitmq/14.7.0
opensearch
----------
* **Current**: `2.23.2`
* **Upgrade**: `2.24.0`
* **Changelog**: https://github.com/opensearch-project/helm-charts/releases/tag/opensearch/opensearch/2.24.0
minio
-----
* **Current**: `14.7.5`
* **Upgrade**: `14.7.8`
* Changelog: https://github.com/bitnami/charts/releases/tag/minio/14.7.8
=> [opencti] upgrade minor dependencies (2024-09-16)

charts/opencti/Chart.yaml, charts/opencti/README.md
minio
-----
* **Current**: `14.7.8`
* **Upgrade**: `14.7.10`
* **Changelog**: https://github.com/bitnami/charts/releases/tag/minio/14.7.10
elasticsearch
-------------
* **Current**: `21.3.16`
* **Upgrade**: `21.3.17`
* **Changelog**: https://github.com/bitnami/charts/releases/tag/elasticsearch/21.3.17
redis
-----
* **Current**: `20.1.3`
* **Upgrade**: `20.1.4`
* **Changelog**: https://github.com/bitnami/charts/releases/tag/redis/20.1.4
opensearch
----------
* **Current**: `2.24.0`
* **Upgrade**: `2.25.0`
* Changelog: https://github.com/opensearch-project/helm-charts/releases/tag/opensearch/opensearch/2.25.0
=> [opencti] upgrade minor dependencies (2024-09-23)

charts/opencti/Chart.yaml, charts/opencti/README.md
minio
-----
* **Current**: `14.7.10`
* **Upgrade**: `14.7.13`
* **Changelog**: https://github.com/bitnami/charts/releases/tag/minio/14.7.13
elasticsearch
-------------
* **Current**: `21.3.17`
* **Upgrade**: `21.3.18`
* **Changelog**: https://github.com/bitnami/charts/releases/tag/elasticsearch/21.3.18
redis
-----
* **Current**: `20.1.4`
* **Upgrade**: `20.1.5`
* **Changelog**: https://github.com/bitnami/charts/releases/tag/redis/20.1.5
=> [opencti] upgrade minor dependencies (2024-09-30)

charts/opencti/Chart.yaml, charts/opencti/README.md
opensearch
----------
* **Current**: `2.25.0`
* **Upgrade**: `2.26.0`
* **Changelog**: https://github.com/opensearch-project/helm-charts/releases/tag/opensearch/opensearch/2.26.0
minio
-----
* **Current**: `14.7.13`
* **Upgrade**: `14.7.15`
* **Changelog**: https://github.com/bitnami/charts/releases/tag/minio/14.7.15
elasticsearch
-------------
* **Current**: `21.3.18`
* **Upgrade**: `21.3.20`
* **Changelog**: https://github.com/bitnami/charts/releases/tag/elasticsearch/21.3.20
redis
-----
* **Current**: `20.1.5`
* **Upgrade**: `20.1.7`
* **Changelog**: https://github.com/bitnami/charts/releases/tag/redis/20.1.7
=> [opencti] upgrade minor dependencies (2024-10-07)

charts/opencti/Chart.yaml, charts/opencti/README.md
elasticsearch
-------------
* **Current**: `21.3.20`
* **Upgrade**: `21.3.21`
* **Changelog**: https://github.com/bitnami/charts/releases/tag/elasticsearch/21.3.21
redis
-----
* **Current**: `20.1.7`
* **Upgrade**: `20.2.0`
* **Changelog**: https://github.com/bitnami/charts/releases/tag/redis/20.2.0
rabbitmq
--------
* **Current**: `15.0.1`
* **Upgrade**: `15.0.2`
* **Changelog**: https://github.com/bitnami/charts/releases/tag/rabbitmq/15.0.2
=> [opencti] upgrade minor dependencies (2024-10-14)

charts/opencti/Chart.yaml
- :information_source: Current: `6.3.5`
- :up: Upgrade: `6.3.6`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.3.6
=> [opencti] new release: 6.3.6

charts/opencti/Chart.yaml, charts/opencti/README.md
rabbitmq
--------
* **Current**: `15.0.2`
* **Upgrade**: `15.0.3`
* **Changelog**: https://github.com/bitnami/charts/releases/tag/rabbitmq/15.0.3
minio
-----
* **Current**: `14.7.15`
* **Upgrade**: `14.8.0`
* **Changelog**: https://github.com/bitnami/charts/releases/tag/minio/14.8.0
elasticsearch
-------------
* **Current**: `21.3.21`
* **Upgrade**: `21.3.22`
* **Changelog**: https://github.com/bitnami/charts/releases/tag/elasticsearch/21.3.22
redis
-----
* **Current**: `20.2.0`
* **Upgrade**: `20.2.1`
* Changelog: https://github.com/bitnami/charts/releases/tag/redis/20.2.1
=> [opencti] upgrade minor dependencies (2024-10-21)

charts/opencti/Chart.yaml, charts/opencti/README.md
opensearch
----------
* **Current**: `2.26.0`
* **Upgrade**: `2.26.1`
* **Changelog**: https://github.com/opensearch-project/helm-charts/releases/tag/opensearch/opensearch/2.26.1
=> [opencti] upgrade minor dependencies (2024-10-28)

charts/opencti/templates/connector/deployment.yaml, charts/opencti/values.yaml
Adds support for global connector settings for:
1. `envFromSecret` settings,
2. `env` settings (previously defined in `values.yaml` but no implemented in deployment),
3. `volumes` on the Pod,
4. `volumeMounts` to be mounted in the containers.
This has been tested locally to provide certificate volume mounts and connector configurations supporting access to the `opencti-server` services over HTTPS with SSL verification enabled for a private but locally trusted certificate.
=> Add support for global connector envFromSecret, env, volumes, and volumeMounts.

charts/opencti/Chart.yaml
- :information_source: Current: `6.3.7`
- :up: Upgrade: `6.3.8`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.3.8
=> [opencti] new release: 6.3.8

charts/opencti/Chart.yaml
- :information_source: Current: `6.3.8`
- :up: Upgrade: `6.3.9`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.3.9
=> [opencti] new release: 6.3.9

charts/opencti/Chart.yaml, charts/opencti/README.md
rabbitmq
--------
* **Current**: `15.0.3`
* **Upgrade**: `15.0.5`
* **Changelog**: https://github.com/bitnami/charts/releases/tag/rabbitmq/15.0.5
minio
-----
* **Current**: `14.8.0`
* **Upgrade**: `14.8.1`
* **Changelog**: https://github.com/bitnami/charts/releases/tag/minio/14.8.1
=> [opencti] upgrade major dependencies (2024-11-01)

charts/opencti/Chart.yaml
- :information_source: Current: `6.3.9`
- :up: Upgrade: `6.3.10`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.3.10
=> [opencti] new release: 6.3.10

charts/opencti/Chart.yaml
- :information_source: Current: `6.3.10`
- :up: Upgrade: `6.3.11`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.3.11
=> [opencti] new release: 6.3.11

charts/opencti/Chart.yaml
- :information_source: Current: `6.3.11`
- :up: Upgrade: `6.3.13`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.3.13
=> [opencti] new release: 6.3.13

charts/opencti/Chart.yaml
- :information_source: Current: `6.4.5`
- :up: Upgrade: `6.4.6`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.4.6
=> [opencti] new release: 6.4.6

charts/opencti/Chart.yaml
- :information_source: Current: `6.4.6`
- :up: Upgrade: `6.4.7`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.4.7
=> [opencti] new release: 6.4.7

charts/opencti/Chart.yaml
- :information_source: Current: `6.4.7`
- :up: Upgrade: `6.4.8`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.4.8
=> [opencti] new release: 6.4.8

charts/opencti/Chart.yaml
- :information_source: Current: `6.4.8`
- :up: Upgrade: `6.4.9`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.4.9
=> [opencti] new release: 6.4.9

charts/opencti/Chart.yaml
- :information_source: Current: `6.4.9`
- :up: Upgrade: `6.4.10`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.4.10
=> [opencti] new release: 6.4.10

charts/opencti/docs/examples.md, charts/opencti/templates/server/deployment.yaml, charts/opencti/values.yaml
Everything is explained in #111. This PR also updates the doc.
- implements #111
=> Update the readyChecker to check dependencies outside the scope of the main chart

charts/opencti/Chart.yaml
- :information_source: Current: `6.4.10`
- :up: Upgrade: `6.4.11`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.4.11
=> [opencti] new release: 6.4.11

charts/opencti/Chart.yaml
- :information_source: Current: `6.5.0`
- :up: Upgrade: `6.5.1`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.5.1
=> [opencti] new release: 6.5.1

charts/opencti/Chart.yaml
- :information_source: Current: `6.5.1`
- :up: Upgrade: `6.5.2`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.5.2
=> [opencti] new release: 6.5.2

charts/opencti/Chart.yaml
- :information_source: Current: `6.5.3`
- :up: Upgrade: `6.5.4`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.5.4
=> [opencti] new release: 6.5.4

charts/opencti/Chart.yaml
- :information_source: Current: `6.5.5`
- :up: Upgrade: `6.5.6`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.5.6
=> [opencti] new release: 6.5.6

charts/opencti/Chart.yaml
- :information_source: Current: `6.5.6`
- :up: Upgrade: `6.5.7`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.5.7
=> [opencti] new release: 6.5.7

charts/opencti/Chart.yaml
- :information_source: Current: `6.5.7`
- :up: Upgrade: `6.5.8`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.5.8
=> [opencti] new release: 6.5.8

charts/opencti/Chart.yaml
- :information_source: Current: `6.5.9`
- :up: Upgrade: `6.5.10`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.5.10
=> [opencti] new release: 6.5.10

charts/opencti/Chart.yaml
- :information_source: Current: `6.5.10`
- :up: Upgrade: `6.5.11`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.5.11
=> [opencti] new release: 6.5.11

charts/opencti/Chart.yaml
- :information_source: Current: `6.5.11`
- :up: Upgrade: `6.6.1`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.6.1
=> [opencti] new release: 6.6.1

charts/opencti/Chart.yaml
- :information_source: Current: `6.6.1`
- :up: Upgrade: `6.6.3`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.6.3
=> [opencti] new release: 6.6.3

charts/opencti/Chart.yaml
- :information_source: Current: `6.6.3`
- :up: Upgrade: `6.6.4`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.6.4
=> [opencti] new release: 6.6.4

charts/opencti/Chart.yaml
- :information_source: Current: `6.6.4`
- :up: Upgrade: `6.6.5`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.6.5
=> [opencti] new release: 6.6.5

charts/opencti/Chart.yaml
- :information_source: Current: `6.6.5`
- :up: Upgrade: `6.6.6`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.6.6
=> [opencti] new release: 6.6.6

charts/opencti/Chart.yaml
- :information_source: Current: `6.6.6`
- :up: Upgrade: `6.6.7`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.6.7
=> [opencti] new release: 6.6.7

charts/opencti/Chart.yaml
- :information_source: Current: `6.6.7`
- :up: Upgrade: `6.6.8`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.6.8
=> [opencti] new release: 6.6.8

charts/opencti/Chart.yaml
- :information_source: Current: `6.6.8`
- :up: Upgrade: `6.6.9`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.6.9
=> [opencti] new release: 6.6.9

charts/opencti/Chart.yaml
- :information_source: Current: `6.6.9`
- :up: Upgrade: `6.6.10`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.6.10
=> [opencti] new release: 6.6.10

charts/opencti/Chart.yaml
- :information_source: Current: `6.6.10`
- :up: Upgrade: `6.6.11`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.6.11
=> [opencti] new release: 6.6.11

charts/opencti/Chart.yaml
- :information_source: Current: `6.6.11`
- :up: Upgrade: `6.6.12`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.6.12
=> [opencti] new release: 6.6.12

.github/workflows/check-opencti-release.yaml
Potential fix for [https://github.com/devops-ia/helm-opencti/security/code-scanning/3](https://github.com/devops-ia/helm-opencti/security/code-scanning/3)
To fix the issue, we will add a `permissions` block at the workflow level to explicitly define the required permissions. Based on the workflow's actions:
- `contents: write` is needed for creating pull requests and updating the README.md Helm Chart.
- `contents: read` is sufficient for other steps that only read repository files.
- No other permissions appear to be required.
The `permissions` block will be added at the root of the workflow to apply to all jobs.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Potential fix for code scanning alert no. 3: Workflow does not contain permissions

.github/workflows/check-opencti-major-dependencies.yaml
Potential fix for [https://github.com/devops-ia/helm-opencti/security/code-scanning/2](https://github.com/devops-ia/helm-opencti/security/code-scanning/2)
To fix the issue, add a `permissions` block at the root of the workflow to define the minimal permissions required for the `GITHUB_TOKEN`. Based on the workflow's operations, the following permissions are needed:
- `contents: read` for reading repository contents.
- `contents: write` for updating dependencies and committing changes.
- `pull-requests: write` for creating pull requests.
The `permissions` block should be added at the top level of the workflow, ensuring all jobs inherit these permissions unless overridden.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Potential fix for code scanning alert no. 2: Workflow does not contain permissions

.github/workflows/lint-test.yaml
Potential fix for [https://github.com/devops-ia/helm-opencti/security/code-scanning/4](https://github.com/devops-ia/helm-opencti/security/code-scanning/4)
To fix the issue, we will add a `permissions` block at the root of the workflow file. This block will specify the least privileges required for the workflow to function. Based on the steps in the workflow, it appears that only `contents: read` is necessary, as the workflow primarily involves reading repository contents and running tests. No write permissions are required.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Potential fix for code scanning alert no. 4: Workflow does not contain permissions

.github/workflows/check-opencti-minor-dependencies.yaml
Potential fix for [https://github.com/devops-ia/helm-opencti/security/code-scanning/1](https://github.com/devops-ia/helm-opencti/security/code-scanning/1)
To fix the issue, we will add a `permissions` block at the root level of the workflow. This block will define the minimal permissions required for the workflow to function correctly. Based on the workflow's operations, the following permissions are necessary:
- `contents: read` for reading repository contents.
- `contents: write` for creating pull requests and updating files.
- `pull-requests: write` for creating and managing pull requests.
The `permissions` block will be added at the root level to apply to all jobs in the workflow.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Potential fix for code scanning alert no. 1: Workflow does not contain permissions

charts/opencti/Chart.yaml
- :information_source: Current: `6.6.12`
- :up: Upgrade: `6.6.13`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.6.13
=> [opencti] new release: 6.6.13

charts/opencti/Chart.yaml
- :information_source: Current: `6.6.13`
- :up: Upgrade: `6.6.14`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.6.14
=> [opencti] new release: 6.6.14

charts/opencti/Chart.yaml
- :information_source: Current: `6.6.16`
- :up: Upgrade: `6.6.17`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.6.17
=> [opencti] new release: 6.6.17

charts/opencti/Chart.yaml
- :information_source: Current: `6.6.18`
- :up: Upgrade: `6.7.0`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.7.0
=> [opencti] new release: 6.7.0

charts/opencti/Chart.yaml
- :information_source: Current: `6.7.2`
- :up: Upgrade: `6.7.3`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.7.3
=> [opencti] new release: 6.7.3

charts/opencti/Chart.yaml
- :information_source: Current: `6.7.8`
- :up: Upgrade: `6.7.9`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.7.9
=> [opencti] new release: 6.7.9

charts/opencti/Chart.yaml
- :information_source: Current: `6.7.9`
- :up: Upgrade: `6.7.10`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.7.10
=> [opencti] new release: 6.7.10

charts/opencti/Chart.yaml
- :information_source: Current: `6.7.15`
- :up: Upgrade: `6.7.16`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.7.16
=> [opencti] new release: 6.7.16

charts/opencti/Chart.yaml, charts/opencti/README.md
+++++++++++
+ PREPARE +
+++++++++++
Loading Pipeline ".github/updatecli/helm-dependencies.yaml"
SCM repository retrieved: 0
++++++++++++++++++
+ AUTO DISCOVERY +
++++++++++++++++++
++++++++++++
+ PIPELINE +
++++++++++++
##########################
##########################
source: source#dragonfly
----------------
Searching for version matching pattern "~v1"
✔ Docker Image Tag "v1.33.1" found matching pattern "~v1"
target: target#dragonfly
----------------
⚠ - change detected:
* key "$.dependencies[4].version" updated from "v1.32.0" to "v1.33.1", in file "charts/opencti/Chart.yaml"
source: source#rabbitmq
---------------
Searching for version matching pattern "~16"
✔ OCI version "16.0.14" found matching pattern "~16"
source: source#eck-stack
----------------
Searching for version matching …
=> [opencti] upgrade minor dependencies (2025-09-04)

charts/opencti/Chart.yaml, charts/opencti/README.md
+++++++++++
+ PREPARE +
+++++++++++
Loading Pipeline ".github/updatecli/helm-dependencies.yaml"
SCM repository retrieved: 0
++++++++++++++++++
+ AUTO DISCOVERY +
++++++++++++++++++
++++++++++++
+ PIPELINE +
++++++++++++
##########################
##########################
source: source#dragonfly
----------------
Searching for version matching pattern "~v1"
✔ Docker Image Tag "v1.34.1" found matching pattern "~v1"
target: target#dragonfly
----------------
⚠ - change detected:
* key "$.dependencies[4].version" updated from "v1.33.1" to "v1.34.1", in file "charts/opencti/Chart.yaml"
source: source#minio
------------
Searching for version matching pattern "~5"
✔ Helm Chart "minio" version "5.4.0" is found from repository "https://charts.min.io/"
source: source#opensearch
----------------- …
=> [opencti] upgrade minor dependencies (2025-09-22)

charts/opencti/Chart.yaml
- :information_source: Current: `6.8.1`
- :up: Upgrade: `6.8.2`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.8.2
=> [opencti] new release: 6.8.2

charts/opencti/Chart.yaml
- :information_source: Current: `6.8.2`
- :up: Upgrade: `6.8.3`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.8.3
=> [opencti] new release: 6.8.3
