devops-ia/helm-opencti

charts/opencti/Chart.yaml

- :information_source: Current: `6.2.12`
- :up: Upgrade: `6.2.13`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.2.13

[opencti] new release: 6.2.13

---

charts/opencti/Chart.yaml

- :information_source: Current: `6.2.14`
- :up: Upgrade: `6.2.15`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.2.15

[opencti] new release: 6.2.15

---

charts/opencti/templates/connector/deployment.yaml
charts/opencti/templates/worker/deployment.yaml

Issue#36: check  for OPENCTI_TOKEN

---

charts/opencti/Chart.yaml

- :information_source: Current: `6.2.15`
- :up: Upgrade: `6.2.16`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.2.16

[opencti] new release: 6.2.16

---

.github/ct.yaml
.github/workflows/lint-test.yaml
charts/opencti/README.md
charts/opencti/ci/ci-common-values.yaml
charts/opencti/templates/server/hpa.yaml
charts/opencti/templates/server/ingress.yaml
charts/opencti/templates/server/networkpolicy.yaml
charts/opencti/templates/server/pdb.yaml
charts/opencti/templates/server/secret.yaml
charts/opencti/templates/server/serviceaccount.yaml
charts/opencti/templates/server/servicemonitor.yaml
charts/opencti/templates/worker/hpa.yaml
charts/opencti/templates/worker/networkpolicy.yaml
charts/opencti/templates/worker/pdb.yaml
charts/opencti/templates/worker/servicemonitor.yaml
charts/opencti/values.yaml

* Add NetworkPolicy
* Add PDB
* fixes #53 #54
N/A

feat: add networkpolicy and pdb

---

charts/opencti/README.md
charts/opencti/ci/ci-common-values.yaml
charts/opencti/templates/connector/deployment.yaml
charts/opencti/templates/server/deployment.yaml
charts/opencti/templates/worker/deployment.yaml
charts/opencti/values.yaml

- Enable graceful shutdown
- fixes #56 
- N/A

feat: add graceful shutdown

---

charts/opencti/README.md
charts/opencti/templates/connector/deployment.yaml
charts/opencti/templates/server/deployment.yaml
charts/opencti/templates/worker/deployment.yaml
charts/opencti/values.yaml

* Configure `readyChecker` on server, worker and connector
- fixes #63 
N/A

fix: parametrize readyChecker image base

---

charts/opencti/Chart.yaml

- :information_source: Current: `6.3.0`
- :up: Upgrade: `6.3.1`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.3.1

[opencti] new release: 6.3.1

---

charts/opencti/Chart.yaml

- :information_source: Current: `6.3.1`
- :up: Upgrade: `6.3.3`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.3.3

[opencti] new release: 6.3.3

---

charts/opencti/Chart.yaml
charts/opencti/README.md

rabbitmq
--------
* **Current**: `14.7.0`
* **Upgrade**: `15.0.1`
* Changelog: https://github.com/bitnami/charts/releases/tag/rabbitmq/15.0.1

[opencti] upgrade major dependencies (2024-10-01)

---

charts/opencti/Chart.yaml

- :information_source: Current: `6.3.4`
- :up: Upgrade: `6.3.5`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.3.5

[opencti] new release: 6.3.5

---

charts/opencti/Chart.yaml

- :information_source: Current: `6.3.13`
- :up: Upgrade: `6.4.0`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.4.0

[opencti] new release: 6.4.0

---

charts/opencti/Chart.yaml

- :information_source: Current: `6.4.0`
- :up: Upgrade: `6.4.1`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.4.1

[opencti] new release: 6.4.1

---

charts/opencti/Chart.yaml

- :information_source: Current: `6.4.1`
- :up: Upgrade: `6.4.2`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.4.2

[opencti] new release: 6.4.2

---

.github/workflows/lint-test.yaml
charts/opencti/README.md
charts/opencti/ci/ci-common-values.yaml
charts/opencti/templates/connector/deployment.yaml
charts/opencti/templates/server/configmap.yaml
charts/opencti/templates/server/deployment.yaml
charts/opencti/templates/server/secret.yaml
charts/opencti/templates/worker/configmap.yaml
charts/opencti/templates/worker/deployment.yaml
charts/opencti/values.yaml

* (connector) fix secrets reference
* (connector) with their config or use global too
* (global) load data from files
* (global) allow generate configMaps with custom data
* (global) allow initContainers
- fixes #65
- fixes #93 
N/A

feat: load env from files

---

charts/opencti/Chart.yaml

- :information_source: Current: `6.4.2`
- :up: Upgrade: `6.4.3`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.4.3

[opencti] new release: 6.4.3

---

charts/opencti/Chart.yaml

- :information_source: Current: `6.4.3`
- :up: Upgrade: `6.4.4`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.4.4

[opencti] new release: 6.4.4

---

charts/opencti/Chart.yaml

- :information_source: Current: `6.4.4`
- :up: Upgrade: `6.4.5`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.4.5

[opencti] new release: 6.4.5

---

.github/dependabot.yml
.github/workflows/release.yaml
charts/opencti/Chart.yaml
charts/opencti/ci/ci-common-values.yaml

- :information_source: Current: `6.5.4`
- :up: Upgrade: `6.5.5`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.5.5

[opencti] new release: 6.5.5

---

charts/opencti/Chart.yaml

- :information_source: Current: `6.7.1`
- :up: Upgrade: `6.7.2`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.7.2

[opencti] new release: 6.7.2

---

charts/opencti/Chart.yaml

- :information_source: Current: `6.7.3`
- :up: Upgrade: `6.7.4`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.7.4

[opencti] new release: 6.7.4

---

charts/opencti/README.md
charts/opencti/ci/ci-common-values.yaml
charts/opencti/templates/NOTES.txt
charts/opencti/templates/connector/deployment.yaml
charts/opencti/templates/connector/service.yaml
charts/opencti/templates/connector/serviceaccount.yaml
charts/opencti/templates/connector/servicemonitor.yaml
charts/opencti/templates/server/service.yaml
charts/opencti/templates/server/servicemonitor.yaml
charts/opencti/templates/worker/service.yaml
charts/opencti/templates/worker/servicemonitor.yaml
charts/opencti/values.yaml

* Added Service API specification on templates
* Moved `{{ $connectorName }}-service-{{ include "opencti.fullname" $ }}` -> `{{ include "opencti.fullname" $ }}-{{ $connectorName }}-connector`
* Added conditional to check if ServiceMonitor CRD exists
* Updated default values and `ci-common-values.yaml` file
- fixes #192

feat(all): improve services

---

charts/opencti/.helmignore

This PR adds a `.helmignore` file to the OpenCTI Helm chart to exclude files and folders that are not required at runtime.
- Documentation (`docs/`, `README.md`, `README.md.gotmpl`)
- Examples and CI configs (`connector-examples/`, `ci/`)
- Artifact Hub metadata (`artifacthub-repo.yml`)
- Prevents unnecessary files from being packaged and deployed  
- Keeps Helm releases clean and focused — no clutter in your deployment  
- Reduces chart size and aligns with Helm best practices  
- Makes it easier to clone and package the chart directly without manual cleanup
Let me know if you'd like to adjust or extend the ignore list.
- fixes #<issue_number>
- [x ] [DCO](https://github.com/devops-ia/.github/blob/main/CONTRIBUTING.md) signed

Add .helmignore to exclude non-essential files from chart packaging

---

charts/opencti/Chart.yaml

- :information_source: Current: `6.7.4`
- :up: Upgrade: `6.7.5`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.7.5

[opencti] new release: 6.7.5

---

charts/opencti/Chart.yaml

- :information_source: Current: `6.7.6`
- :up: Upgrade: `6.7.7`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.7.7

[opencti] new release: 6.7.7

---

.github/ct.yaml
.github/updatecli/helm-dependencies.yaml
.pre-commit-config.yaml
charts/opencti/Chart.yaml
charts/opencti/README.md
charts/opencti/README.md.gotmpl
charts/opencti/ci/ci-common-values.yaml
charts/opencti/docs/configuration.md
charts/opencti/templates/NOTES.txt
charts/opencti/values.yaml

* Based on #209, we replaced Bitnami Helm charts (except `RabbitMQ`, looking for a solution...):
* `bitnami/minio` -> `minio official chart`
* `bitnami/redis` -> `dragonfly official chart`
* `bitnami/elasticsearch` -> `eck-stack official chart`
* Update docs
* Update values
* Update examples
* Update updatecli config to keep update deps
- closes #212 
- closes #213 
- closes #214

feat: use oss services instead bitnami charts

---

charts/opencti/Chart.yaml

- :information_source: Current: `6.7.10`
- :up: Upgrade: `6.7.11`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.7.11

[opencti] new release: 6.7.11

---

charts/opencti/Chart.yaml

- :information_source: Current: `6.7.14`
- :up: Upgrade: `6.7.15`
Changelog: https://github.com/OpenCTI-Platform/opencti/releases/tag/6.7.15

[opencti] new release: 6.7.15
